version: '3.1'

services:

  elasticsearch:
    image: elasticsearch:6.5.4
    container_name: elasticsearch
    hostname: elasticsearch
    ports:
      - "9200:9200"
    expose:
      - "9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elastic-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  kibana:
    image: kibana:6.5.4
    container_name: kibana
    ports:
      - "5601:5601"
    expose:
      - "5601"
    environment:
      - SERVER_NAME=kibana.localhost
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
    depends_on:
      - elasticsearch
    networks:
      - elastic-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  elastic-network:
    name: elastic
    external: true

volumes:
  elasticsearch-data:
